import '../models/product.dart';
import '../models/category.dart';
import '../models/user.dart';

class SampleDataService {
  static List<String> getProductImages(String category, String productTitle) {
    // Return specific images based on product type
    switch (category.toLowerCase()) {
      case 'electronics':
        if (productTitle.toLowerCase().contains('iphone')) {
          return [
            'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('macbook')) {
          return [
            'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('tv') || productTitle.toLowerCase().contains('television')) {
          return [
            'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('gaming') || productTitle.toLowerCase().contains('pc')) {
          return [
            'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('camera')) {
          return [
            'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1581591524425-c7e0978865fc?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('headphone') || productTitle.toLowerCase().contains('airpod')) {
          return [
            'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('tablet') || productTitle.toLowerCase().contains('ipad')) {
          return [
            'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1589739900266-43b2843f4c12?w=500&h=500&fit=crop',
          ];
        }
        return [
          'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&h=500&fit=crop',
        ];

      case 'vehicles':
        if (productTitle.toLowerCase().contains('honda') || productTitle.toLowerCase().contains('civic')) {
          return [
            'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1494905998402-395d579af36f?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('bike') || productTitle.toLowerCase().contains('trek')) {
          return [
            'https://images.unsplash.com/photo-1544191696-15693072e0b5?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('toyota') || productTitle.toLowerCase().contains('camry')) {
          return [
            'https://images.unsplash.com/photo-1550355291-bbee04a92027?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('ford') || productTitle.toLowerCase().contains('mustang')) {
          return [
            'https://images.unsplash.com/photo-1584345604476-8ec5f82d661c?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1581650107963-3e8c1f48241b?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('tesla')) {
          return [
            'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1561580125-028ee3bd62eb?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1562053349-41b5ccc2b6c1?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('motorcycle') || productTitle.toLowerCase().contains('harley')) {
          return [
            'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1558981852-426c6c22a060?w=500&h=500&fit=crop',
          ];
        }
        return [
          'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=500&h=500&fit=crop',
        ];

      case 'home & garden':
        if (productTitle.toLowerCase().contains('sofa') || productTitle.toLowerCase().contains('sectional')) {
          return [
            'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('dining') || productTitle.toLowerCase().contains('table')) {
          return [
            'https://images.unsplash.com/photo-1449247709967-d4461a6a6103?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1506439753458-613966752a9e?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1506439753458-6e0eb8cfb237?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('bed') || productTitle.toLowerCase().contains('mattress')) {
          return [
            'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('lamp') || productTitle.toLowerCase().contains('lighting')) {
          return [
            'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('rug') || productTitle.toLowerCase().contains('carpet')) {
          return [
            'https://images.unsplash.com/photo-1575414003591-ece8d0416c7a?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1600166898405-da9535204843?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1584346133934-7a7b82ad5e1f?w=500&h=500&fit=crop',
          ];
        }
        return [
          'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&h=500&fit=crop',
        ];

      case 'fashion':
        if (productTitle.toLowerCase().contains('handbag') || productTitle.toLowerCase().contains('louis vuitton')) {
          return [
            'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('nike') || productTitle.toLowerCase().contains('jordan')) {
          return [
            'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('watch') || productTitle.toLowerCase().contains('rolex')) {
          return [
            'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('dress') || productTitle.toLowerCase().contains('gown')) {
          return [
            'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('jacket') || productTitle.toLowerCase().contains('coat')) {
          return [
            'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1548883354-94bcfe321cbb?w=500&h=500&fit=crop',
          ];
        }
        return [
          'https://images.unsplash.com/photo-1445205170230-053b83016050?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=500&h=500&fit=crop',
        ];

      case 'sports & recreation':
        if (productTitle.toLowerCase().contains('golf')) {
          return [
            'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('treadmill')) {
          return [
            'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('tennis')) {
          return [
            'https://images.unsplash.com/photo-1617083934555-ac7d0a8c1252?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1622279457486-28f95266f1b2?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('basketball')) {
          return [
            'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('yoga')) {
          return [
            'https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1545389336-cf090694435e?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1510894347713-fc3ed6fdf539?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('camping')) {
          return [
            'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=500&h=500&fit=crop',
          ];
        }
        return [
          'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=500&h=500&fit=crop',
        ];

      case 'books & media':
        if (productTitle.toLowerCase().contains('harry potter')) {
          return [
            'https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('vinyl') || productTitle.toLowerCase().contains('record')) {
          return [
            'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1526394931762-8a4116f6e8c7?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('textbook') || productTitle.toLowerCase().contains('computer science')) {
          return [
            'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('dvd') || productTitle.toLowerCase().contains('movie')) {
          return [
            'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1616530940355-351fabd9524b?w=500&h=500&fit=crop',
          ];
        }
        return [
          'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&h=500&fit=crop',
        ];

      case 'pets & animals':
        if (productTitle.toLowerCase().contains('dog') || productTitle.toLowerCase().contains('crate')) {
          return [
            'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('cat') || productTitle.toLowerCase().contains('tree')) {
          return [
            'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('aquarium') || productTitle.toLowerCase().contains('fish')) {
          return [
            'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('bird') || productTitle.toLowerCase().contains('cage')) {
          return [
            'https://images.unsplash.com/photo-1520808663317-647b476a81b9?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=500&h=500&fit=crop',
          ];
        }
        return [
          'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=500&h=500&fit=crop',
        ];

      case 'services':
        if (productTitle.toLowerCase().contains('web') || productTitle.toLowerCase().contains('development')) {
          return [
            'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('photography')) {
          return [
            'https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('cleaning')) {
          return [
            'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=500&h=500&fit=crop',
          ];
        } else if (productTitle.toLowerCase().contains('tutor') || productTitle.toLowerCase().contains('teaching')) {
          return [
            'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=500&h=500&fit=crop',
            'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=500&h=500&fit=crop',
          ];
        }
        return [
          'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=500&h=500&fit=crop',
        ];

      default:
        return [
          'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=500&h=500&fit=crop',
        ];
    }
  }

  // Update the getSampleProducts method to ensure each category has at least 10 products
  static List<Product> getSampleProducts() {
    final sampleUsers = getSampleUsers();
    final sampleCategories = getSampleCategories();

    // Create a list to hold all products
    List<Product> allProducts = [];

    // Electronics products (10 products)
    allProducts.addAll([
      Product(
        id: 1,
        userId: 1,
        categoryId: 1,
        title: 'iPhone 14 Pro Max - Excellent Condition',
        description: 'Barely used iPhone 14 Pro Max in excellent condition. Comes with original box, charger, and screen protector already applied. No scratches or dents. Battery health at 98%. Perfect for anyone looking for a premium smartphone experience.',
        price: 899.99,
        condition: 'used',
        location: 'New York, NY',
        latitude: 40.7128,
        longitude: -74.0060,
        images: getProductImages('Electronics', 'iPhone 14 Pro Max - Excellent Condition'),
        status: 'active',
        views: 245,
        isFeatured: true,
        user: sampleUsers[0],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        updatedAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
      Product(
        id: 2,
        userId: 2,
        categoryId: 1,
        title: 'MacBook Air M2 2022 - Like New',
        description: 'MacBook Air with M2 chip, 8GB RAM, 256GB SSD. Used for only 3 months. Perfect for students and professionals. Includes original charger and box. No scratches, works perfectly.',
        price: 1099.00,
        condition: 'used',
        location: 'Los Angeles, CA',
        latitude: 34.0522,
        longitude: -118.2437,
        images: getProductImages('Electronics', 'MacBook Air M2 2022 - Like New'),
        status: 'active',
        views: 189,
        isFeatured: true,
        user: sampleUsers[1],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      Product(
        id: 7,
        userId: 3,
        categoryId: 1,
        title: 'Gaming PC - High Performance',
        description: 'Custom built gaming PC with RTX 3080, Intel i7-12700K, 32GB RAM, 1TB NVMe SSD. Perfect for gaming and content creation. Runs all modern games at max settings.',
        price: 1899.99,
        condition: 'used',
        location: 'Houston, TX',
        latitude: 29.7604,
        longitude: -95.3698,
        images: getProductImages('Electronics', 'Gaming PC - High Performance'),
        status: 'active',
        views: 298,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Product(
        id: 9,
        userId: 1,
        categoryId: 1,
        title: 'Samsung 65" 4K Smart TV',
        description: 'Brand new Samsung 65-inch 4K UHD Smart TV. Still in original packaging. Perfect for home entertainment setup. Latest model with all smart features.',
        price: 649.99,
        condition: 'new',
        location: 'Chicago, IL',
        latitude: 41.8781,
        longitude: -87.6298,
        images: getProductImages('Electronics', 'Samsung 65" 4K Smart TV'),
        status: 'active',
        views: 156,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(hours: 8)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 8)),
      ),
      Product(
        id: 101,
        userId: 2,
        categoryId: 1,
        title: 'Sony Alpha A7 III Camera - Full Frame',
        description: 'Sony Alpha A7 III mirrorless camera with 24.2MP full-frame sensor. Includes 28-70mm lens, extra battery, and 64GB memory card. Perfect for professional photography and videography.',
        price: 1799.99,
        condition: 'used',
        location: 'Miami, FL',
        latitude: 25.7617,
        longitude: -80.1918,
        images: getProductImages('Electronics', 'Camera'),
        status: 'active',
        views: 178,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
        updatedAt: DateTime.now().subtract(const Duration(days: 6)),
      ),
      Product(
        id: 102,
        userId: 3,
        categoryId: 1,
        title: 'Apple AirPods Pro - Noise Cancelling',
        description: 'Apple AirPods Pro with active noise cancellation. Used for 2 months, perfect condition. Includes original box and all ear tips. Great sound quality and battery life.',
        price: 179.99,
        condition: 'used',
        location: 'Seattle, WA',
        latitude: 47.6062,
        longitude: -122.3321,
        images: getProductImages('Electronics', 'AirPods'),
        status: 'active',
        views: 210,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        updatedAt: DateTime.now().subtract(const Duration(days: 4)),
      ),
      Product(
        id: 103,
        userId: 4,
        categoryId: 1,
        title: 'iPad Pro 12.9" 2022 - 256GB',
        description: 'iPad Pro 12.9-inch 2022 model with M2 chip, 256GB storage. Includes Apple Pencil 2nd generation and Smart Keyboard Folio. Perfect for digital artists and professionals.',
        price: 1099.99,
        condition: 'used',
        location: 'Boston, MA',
        latitude: 42.3601,
        longitude: -71.0589,
        images: getProductImages('Electronics', 'iPad'),
        status: 'active',
        views: 165,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now().subtract(const Duration(days: 7)),
      ),
      Product(
        id: 104,
        userId: 1,
        categoryId: 1,
        title: 'Bose QuietComfort 45 Headphones',
        description: 'Bose QuietComfort 45 wireless noise-cancelling headphones. Excellent sound quality and comfort for long listening sessions. Includes carrying case and all accessories.',
        price: 249.99,
        condition: 'used',
        location: 'Denver, CO',
        latitude: 39.7392,
        longitude: -104.9903,
        images: getProductImages('Electronics', 'Headphone'),
        status: 'active',
        views: 142,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
        updatedAt: DateTime.now().subtract(const Duration(days: 9)),
      ),
      Product(
        id: 105,
        userId: 2,
        categoryId: 1,
        title: 'Nintendo Switch OLED - White',
        description: 'Nintendo Switch OLED model in white. Includes original box, dock, Joy-Cons, and all accessories. Also comes with 3 games: Mario Kart 8, Zelda BOTW, and Animal Crossing.',
        price: 329.99,
        condition: 'used',
        location: 'Portland, OR',
        latitude: 45.5051,
        longitude: -122.6750,
        images: [
          'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 198,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        updatedAt: DateTime.now().subtract(const Duration(days: 8)),
      ),
      Product(
        id: 106,
        userId: 3,
        categoryId: 1,
        title: 'Dell XPS 15 Laptop - i9/32GB/1TB',
        description: 'Dell XPS 15 laptop with Intel i9 processor, 32GB RAM, 1TB SSD, and NVIDIA RTX 3050Ti graphics. 4K OLED touch display. Perfect for professionals and content creators.',
        price: 1799.99,
        condition: 'used',
        location: 'Austin, TX',
        latitude: 30.2672,
        longitude: -97.7431,
        images: [
          'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 176,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[0],
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        updatedAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
    ]);

    // Vehicles products (10 products)
    allProducts.addAll([
      Product(
        id: 3,
        userId: 3,
        categoryId: 2,
        title: '2020 Honda Civic - Low Mileage',
        description: '2020 Honda Civic with only 25,000 miles. Excellent fuel economy, reliable transportation. Clean title, no accidents. Regular maintenance records available. Perfect first car or commuter vehicle.',
        price: 18500.00,
        condition: 'used',
        location: 'Phoenix, AZ',
        latitude: 33.4484,
        longitude: -112.0740,
        images: getProductImages('Vehicles', '2020 Honda Civic - Low Mileage'),
        status: 'active',
        views: 412,
        isFeatured: true,
        user: sampleUsers[2],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
      Product(
        id: 8,
        userId: 4,
        categoryId: 2,
        title: 'Mountain Bike - Trek X-Caliber 8',
        description: 'Trek X-Caliber 8 mountain bike in great condition. Perfect for trail riding and commuting. Recently serviced with new tires and brake pads.',
        price: 899.00,
        condition: 'used',
        location: 'New York, NY',
        latitude: 40.7128,
        longitude: -74.0060,
        images: getProductImages('Vehicles', 'Mountain Bike - Trek X-Caliber 8'),
        status: 'active',
        views: 87,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(hours: 18)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 18)),
      ),
      Product(
        id: 13,
        userId: 1,
        categoryId: 2,
        title: 'Toyota Camry 2019 - Well Maintained',
        description: 'Toyota Camry 2019 with 35,000 miles. Well maintained, regular service, no accidents. Fuel efficient and reliable family sedan.',
        price: 16500.00,
        condition: 'used',
        location: 'Dallas, TX',
        latitude: 32.7767,
        longitude: -96.7970,
        images: getProductImages('Vehicles', 'Toyota Camry 2019 - Well Maintained'),
        status: 'active',
        views: 175,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now().subtract(const Duration(days: 7)),
      ),
      Product(
        id: 107,
        userId: 2,
        categoryId: 2,
        title: '2018 Ford Mustang GT - Premium',
        description: '2018 Ford Mustang GT Premium with 5.0L V8 engine. Only 30,000 miles. Performance package, leather interior, and premium sound system. Excellent condition with no accidents.',
        price: 32500.00,
        condition: 'used',
        location: 'San Diego, CA',
        latitude: 32.7157,
        longitude: -117.1611,
        images: getProductImages('Vehicles', 'Ford Mustang'),
        status: 'active',
        views: 320,
        isFeatured: true,
        user: sampleUsers[1],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Product(
        id: 108,
        userId: 3,
        categoryId: 2,
        title: 'Tesla Model 3 2021 - Long Range',
        description: '2021 Tesla Model 3 Long Range with only 15,000 miles. Dual motor all-wheel drive, premium interior, and full self-driving capability. Perfect condition, one owner.',
        price: 42999.00,
        condition: 'used',
        location: 'Seattle, WA',
        latitude: 47.6062,
        longitude: -122.3321,
        images: getProductImages('Vehicles', 'Tesla'),
        status: 'active',
        views: 405,
        isFeatured: true,
        user: sampleUsers[2],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        updatedAt: DateTime.now().subtract(const Duration(days: 4)),
      ),
      Product(
        id: 109,
        userId: 4,
        categoryId: 2,
        title: 'Harley-Davidson Sportster 883 - 2019',
        description: '2019 Harley-Davidson Sportster 883 with only 3,500 miles. Excellent condition, garage kept. Includes windshield, saddlebags, and custom exhaust. Perfect for cruising.',
        price: 8500.00,
        condition: 'used',
        location: 'Austin, TX',
        latitude: 30.2672,
        longitude: -97.7431,
        images: getProductImages('Vehicles', 'Motorcycle'),
        status: 'active',
        views: 267,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
        updatedAt: DateTime.now().subtract(const Duration(days: 6)),
      ),
      Product(
        id: 110,
        userId: 1,
        categoryId: 2,
        title: 'Specialized Rockhopper Mountain Bike',
        description: 'Specialized Rockhopper mountain bike in excellent condition. 29-inch wheels, hydraulic disc brakes, and front suspension. Perfect for trails and off-road riding.',
        price: 650.00,
        condition: 'used',
        location: 'Denver, CO',
        latitude: 39.7392,
        longitude: -104.9903,
        images: [
          'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        updatedAt: DateTime.now().subtract(const Duration(days: 8)),
      ),
      Product(
        id: 111,
        userId: 2,
        categoryId: 2,
        title: '2017 Jeep Wrangler Unlimited - Rubicon',
        description: '2017 Jeep Wrangler Unlimited Rubicon with 45,000 miles. 4x4, hardtop, lifted with 33" tires. Winch, LED lights, and many upgrades. Perfect for off-road adventures.',
        price: 34500.00,
        condition: 'used',
        location: 'Phoenix, AZ',
        latitude: 33.4484,
        longitude: -112.0740,
        images: [
          'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 289,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
        updatedAt: DateTime.now().subtract(const Duration(days: 9)),
      ),
      Product(
        id: 112,
        userId: 3,
        categoryId: 2,
        title: 'Vespa Primavera 150 Scooter - 2020',
        description: '2020 Vespa Primavera 150 scooter with only 1,200 miles. Perfect condition, always garaged. Includes windshield, rear rack, and top case. Fun and economical transportation.',
        price: 4200.00,
        condition: 'used',
        location: 'Miami, FL',
        latitude: 25.7617,
        longitude: -80.1918,
        images: [
          'https://images.unsplash.com/photo-1598983872648-a3c3774b0c4e?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 156,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        updatedAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
      Product(
        id: 113,
        userId: 4,
        categoryId: 2,
        title: '2022 Subaru Outback - Wilderness Edition',
        description: '2022 Subaru Outback Wilderness Edition with only 8,000 miles. All-wheel drive, raised suspension, and all-terrain tires. Perfect for outdoor adventures and all weather conditions.',
        price: 36500.00,
        condition: 'used',
        location: 'Portland, OR',
        latitude: 45.5051,
        longitude: -122.6750,
        images: [
          'https://images.unsplash.com/photo-1669215420018-098507d14861?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 210,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[1],
        createdAt: DateTime.now().subtract(const Duration(days: 11)),
        updatedAt: DateTime.now().subtract(const Duration(days: 11)),
      ),
    ]);

    // Home & Garden products (10 products)
    allProducts.addAll([
      Product(
        id: 4,
        userId: 1,
        categoryId: 3,
        title: 'Sectional Sofa - Modern Design',
        description: 'Beautiful modern sectional sofa in gray fabric. Very comfortable and in excellent condition. Perfect for living room. Seats 6 people comfortably. Pet-free and smoke-free home.',
        price: 799.99,
        condition: 'used',
        location: 'Los Angeles, CA',
        latitude: 34.0522,
        longitude: -118.2437,
        images: getProductImages('Home & Garden', 'Sectional Sofa - Modern Design'),
        status: 'active',
        views: 134,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(hours: 12)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 12)),
      ),
      Product(
        id: 11,
        userId: 3,
        categoryId: 3,
        title: 'Dining Table Set - 6 Chairs',
        description: 'Solid wood dining table with 6 matching chairs. Perfect for family dinners and entertaining guests. Excellent condition, no scratches or damage.',
        price: 599.00,
        condition: 'used',
        location: 'Chicago, IL',
        latitude: 41.8781,
        longitude: -87.6298,
        images: getProductImages('Home & Garden', 'Dining Table Set - 6 Chairs'),
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      Product(
        id: 14,
        userId: 2,
        categoryId: 3,
        title: 'Modern Coffee Table - Glass Top',
        description: 'Modern coffee table with glass top and wooden legs. Elegant design that fits any living room decor. Excellent condition.',
        price: 249.99,
        condition: 'used',
        location: 'Miami, FL',
        latitude: 25.7617,
        longitude: -80.1918,
        images: getProductImages('Home & Garden', 'Table'),
        status: 'active',
        views: 65,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        updatedAt: DateTime.now().subtract(const Duration(days: 4)),
      ),
      Product(
        id: 114,
        userId: 4,
        categoryId: 3,
        title: 'King Size Bed Frame with Mattress',
        description: 'King size bed frame with memory foam mattress. Solid wood frame in dark walnut finish. Mattress is only 1 year old and in perfect condition. Includes two matching nightstands.',
        price: 899.99,
        condition: 'used',
        location: 'Seattle, WA',
        latitude: 47.6062,
        longitude: -122.3321,
        images: getProductImages('Home & Garden', 'Bed'),
        status: 'active',
        views: 142,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Product(
        id: 115,
        userId: 1,
        categoryId: 3,
        title: 'Vintage Floor Lamp - Brass Finish',
        description: 'Beautiful vintage floor lamp with brass finish and marble base. Adjustable height and direction. Perfect accent piece for any living room or reading nook.',
        price: 175.00,
        condition: 'used',
        location: 'Boston, MA',
        latitude: 42.3601,
        longitude: -71.0589,
        images: getProductImages('Home & Garden', 'Lamp'),
        status: 'active',
        views: 87,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
        updatedAt: DateTime.now().subtract(const Duration(days: 6)),
      ),
      Product(
        id: 116,
        userId: 2,
        categoryId: 3,
        title: 'Persian Area Rug - 8x10 Handmade',
        description: 'Authentic Persian area rug, 8x10 feet. Handmade with 100% wool. Beautiful traditional pattern in red, blue, and beige. Excellent condition, professionally cleaned.',
        price: 1200.00,
        condition: 'used',
        location: 'Denver, CO',
        latitude: 39.7392,
        longitude: -104.9903,
        images: getProductImages('Home & Garden', 'Rug'),
        status: 'active',
        views: 110,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now().subtract(const Duration(days: 7)),
      ),
      Product(
        id: 117,
        userId: 3,
        categoryId: 3,
        title: 'Outdoor Patio Set - Table and 6 Chairs',
        description: 'Outdoor patio dining set with glass-top table and 6 chairs with cushions. Weather-resistant aluminum frame. Perfect for outdoor entertaining and summer barbecues.',
        price: 450.00,
        condition: 'used',
        location: 'Phoenix, AZ',
        latitude: 33.4484,
        longitude: -112.0740,
        images: [
          'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        updatedAt: DateTime.now().subtract(const Duration(days: 8)),
      ),
      Product(
        id: 118,
        userId: 4,
        categoryId: 3,
        title: 'Dyson V11 Vacuum - Barely Used',
        description: 'Dyson V11 cordless vacuum cleaner. Barely used, perfect condition. Includes all attachments and wall mount charging dock. Powerful suction and great battery life.',
        price: 399.99,
        condition: 'used',
        location: 'Austin, TX',
        latitude: 30.2672,
        longitude: -97.7431,
        images: [
          'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 176,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
        updatedAt: DateTime.now().subtract(const Duration(days: 9)),
      ),
      Product(
        id: 119,
        userId: 1,
        categoryId: 3,
        title: 'KitchenAid Stand Mixer - Professional',
        description: 'KitchenAid Professional 600 Series stand mixer in red. 6-quart bowl capacity. Includes all standard attachments plus pasta maker. Used only a few times, like new condition.',
        price: 325.00,
        condition: 'used',
        location: 'Portland, OR',
        latitude: 45.5051,
        longitude: -122.6750,
        images: [
          'https://images.unsplash.com/photo-1594487637146-282a20ad1e70?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1578738288760-05ce9be719d3?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 143,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        updatedAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
      Product(
        id: 120,
        userId: 2,
        categoryId: 3,
        title: 'Indoor Plant Collection - 5 Plants',
        description: 'Collection of 5 healthy indoor plants: Monstera, Fiddle Leaf Fig, Snake Plant, Pothos, and ZZ Plant. All in decorative pots. Perfect for adding greenery to your home or office.',
        price: 150.00,
        condition: 'new',
        location: 'San Diego, CA',
        latitude: 32.7157,
        longitude: -117.1611,
        images: [
          'https://images.unsplash.com/photo-1463320726281-696a485928c7?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1545165375-7c5efd26f353?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 89,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[2],
        createdAt: DateTime.now().subtract(const Duration(days: 11)),
        updatedAt: DateTime.now().subtract(const Duration(days: 11)),
      ),
    ]);

    // Fashion products (10 products)
    allProducts.addAll([
      Product(
        id: 5,
        userId: 4,
        categoryId: 4,
        title: 'Designer Handbag - Louis Vuitton',
        description: 'Authentic Louis Vuitton handbag in excellent condition. Comes with authenticity certificate and dust bag. Purchased from official LV store. Perfect for special occasions or everyday luxury.',
        price: 1299.99,
        condition: 'used',
        location: 'Houston, TX',
        latitude: 29.7604,
        longitude: -95.3698,
        images: getProductImages('Fashion', 'Designer Handbag - Louis Vuitton'),
        status: 'active',
        views: 267,
        isFeatured: true,
        user: sampleUsers[3],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        updatedAt: DateTime.now().subtract(const Duration(days: 4)),
      ),
      Product(
        id: 10,
        userId: 2,
        categoryId: 4,
        title: 'Nike Air Jordan 1 - Size 10',
        description: 'Classic Nike Air Jordan 1 sneakers in size 10. Gently used, great condition. Perfect for sneaker collectors or everyday wear. Authentic with original box.',
        price: 189.99,
        condition: 'used',
        location: 'Phoenix, AZ',
        latitude: 33.4484,
        longitude: -112.0740,
        images: getProductImages('Fashion', 'Nike Air Jordan 1 - Size 10'),
        status: 'active',
        views: 156,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(hours: 4)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 4)),
      ),
      Product(
        id: 15,
        userId: 3,
        categoryId: 4,
        title: 'Designer Sunglasses - Ray-Ban',
        description: 'Authentic Ray-Ban Wayfarer sunglasses. Classic design, barely used. Comes with original case and cleaning cloth.',
        price: 89.99,
        condition: 'used',
        location: 'San Francisco, CA',
        latitude: 37.7749,
        longitude: -122.4194,
        images: [
          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 82,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
      Product(
        id: 121,
        userId: 1,
        categoryId: 4,
        title: 'Rolex Submariner Watch - Authentic',
        description: 'Authentic Rolex Submariner watch in stainless steel. Purchased in 2019, excellent condition with minimal wear. Includes original box, papers, and extra links. A timeless luxury timepiece.',
        price: 9500.00,
        condition: 'used',
        location: 'Miami, FL',
        latitude: 25.7617,
        longitude: -80.1918,
        images: getProductImages('Fashion', 'Watch'),
        status: 'active',
        views: 320,
        isFeatured: true,
        user: sampleUsers[0],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Product(
        id: 122,
        userId: 2,
        categoryId: 4,
        title: 'Designer Evening Dress - Size 8',
        description: 'Elegant black evening dress, size 8. Worn only once to a formal event. Perfect for special occasions, weddings, or formal dinners. Dry cleaned and ready to wear.',
        price: 299.99,
        condition: 'used',
        location: 'Chicago, IL',
        latitude: 41.8781,
        longitude: -87.6298,
        images: getProductImages('Fashion', 'Dress'),
        status: 'active',
        views: 145,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
        updatedAt: DateTime.now().subtract(const Duration(days: 6)),
      ),
      Product(
        id: 123,
        userId: 3,
        categoryId: 4,
        title: 'Leather Jacket - Genuine Leather',
        description: 'Genuine leather jacket in black. Size medium. Classic biker style with zippers and pockets. Excellent quality and condition. Perfect for casual wear or motorcycle riding.',
        price: 199.99,
        condition: 'used',
        location: 'Denver, CO',
        latitude: 39.7392,
        longitude: -104.9903,
        images: getProductImages('Fashion', 'Jacket'),
        status: 'active',
        views: 167,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now().subtract(const Duration(days: 7)),
      ),
      Product(
        id: 124,
        userId: 4,
        categoryId: 4,
        title: 'Gucci Belt - Authentic Designer',
        description: 'Authentic Gucci belt with GG buckle. Size 85cm/34 inches. Comes with original box and dust bag. Perfect condition, barely worn. A luxury accessory for any wardrobe.',
        price: 350.00,
        condition: 'used',
        location: 'Los Angeles, CA',
        latitude: 34.0522,
        longitude: -118.2437,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 198,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        updatedAt: DateTime.now().subtract(const Duration(days: 8)),
      ),
      Product(
        id: 125,
        userId: 1,
        categoryId: 4,
        title: 'Adidas Ultraboost 22 - Size 9',
        description: 'Adidas Ultraboost 22 running shoes in white/black colorway. Size 9. Lightly used for casual wear only. Excellent cushioning and comfort. Includes original box.',
        price: 129.99,
        condition: 'used',
        location: 'Seattle, WA',
        latitude: 47.6062,
        longitude: -122.3321,
        images: [
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 134,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
        updatedAt: DateTime.now().subtract(const Duration(days: 9)),
      ),
      Product(
        id: 126,
        userId: 2,
        categoryId: 4,
        title: 'Vintage Denim Jacket - Levi\'s',
        description: 'Vintage Levi\'s denim jacket from the 90s. Size large. Classic blue wash with authentic vintage wear. Perfect for layering and adding a retro touch to any outfit.',
        price: 79.99,
        condition: 'used',
        location: 'Austin, TX',
        latitude: 30.2672,
        longitude: -97.7431,
        images: [
          'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 112,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        updatedAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
      Product(
        id: 127,
        userId: 3,
        categoryId: 4,
        title: 'Coach Purse - Crossbody Bag',
        description: 'Coach crossbody purse in brown leather. Compact size perfect for everyday use. Adjustable strap and multiple compartments. Authentic with care card included.',
        price: 149.99,
        condition: 'used',
        location: 'Boston, MA',
        latitude: 42.3601,
        longitude: -71.0589,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 156,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 11)),
        updatedAt: DateTime.now().subtract(const Duration(days: 11)),
      ),
      Product(
        id: 128,
        userId: 4,
        categoryId: 4,
        title: 'Cashmere Scarf - Luxury Soft',
        description: 'Luxury cashmere scarf in cream color. Incredibly soft and warm. Perfect for winter weather or as an elegant accessory. Dry cleaned and in perfect condition.',
        price: 89.99,
        condition: 'used',
        location: 'Portland, OR',
        latitude: 45.5051,
        longitude: -122.6750,
        images: [
          'https://images.unsplash.com/photo-1445205170230-053b83016050?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
        updatedAt: DateTime.now().subtract(const Duration(days: 12)),
      ),
      Product(
        id: 129,
        userId: 1,
        categoryId: 4,
        title: 'Business Suit - Men\'s 42R',
        description: 'Men\'s business suit in charcoal gray. Size 42R jacket with 36x32 pants. Wool blend fabric, excellent for professional settings. Dry cleaned and pressed, ready to wear.',
        price: 199.99,
        condition: 'used',
        location: 'Atlanta, GA',
        latitude: 33.7490,
        longitude: -84.3880,
        images: [
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 143,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 13)),
        updatedAt: DateTime.now().subtract(const Duration(days: 13)),
      ),
      Product(
        id: 130,
        userId: 2,
        categoryId: 4,
        title: 'Diamond Earrings - 1 Carat Total',
        description: 'Beautiful diamond stud earrings, 1 carat total weight. 14k white gold setting. Excellent clarity and sparkle. Comes with original jewelry box and certificate.',
        price: 899.99,
        condition: 'used',
        location: 'San Diego, CA',
        latitude: 32.7157,
        longitude: -117.1611,
        images: [
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 234,
        isFeatured: true,
        user: sampleUsers[1],
        category: sampleCategories[3],
        createdAt: DateTime.now().subtract(const Duration(days: 14)),
        updatedAt: DateTime.now().subtract(const Duration(days: 14)),
      ),
    ]);

    // Sports & Recreation products (10 products)
    allProducts.addAll([
      Product(
        id: 131,
        userId: 3,
        categoryId: 5,
        title: 'Callaway Golf Club Set - Like New',
        description: 'Callaway golf club set in excellent condition. Includes driver, fairway wood, hybrid, irons, and putter. Perfect for beginners or intermediate players.',
        price: 499.99,
        condition: 'used',
        location: 'Scottsdale, AZ',
        latitude: 33.5098,
        longitude: -111.9210,
        images: getProductImages('Sports & Recreation', 'Golf'),
        status: 'active',
        views: 123,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
      Product(
        id: 132,
        userId: 4,
        categoryId: 5,
        title: 'NordicTrack Treadmill - Excellent Condition',
        description: 'NordicTrack treadmill with interactive display and incline/decline features. Used for only 6 months, like new condition. Perfect for home workouts.',
        price: 799.00,
        condition: 'used',
        location: 'Salt Lake City, UT',
        latitude: 40.7608,
        longitude: -111.8910,
        images: getProductImages('Sports & Recreation', 'Treadmill'),
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Product(
        id: 133,
        userId: 1,
        categoryId: 5,
        title: 'Wilson Tennis Racquet - Pro Staff',
        description: 'Wilson Pro Staff tennis racquet in excellent condition. Strung with premium strings. Perfect for advanced players.',
        price: 129.99,
        condition: 'used',
        location: 'Santa Monica, CA',
        latitude: 34.0083,
        longitude: -118.4960,
        images: getProductImages('Sports & Recreation', 'Tennis'),
        status: 'active',
        views: 76,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now().subtract(const Duration(days: 7)),
      ),
      Product(
        id: 134,
        userId: 2,
        categoryId: 5,
        title: 'Spalding Basketball - Official Size',
        description: 'Spalding NBA official size basketball. Used for only a few games, excellent grip and bounce. Perfect for indoor or outdoor play.',
        price: 29.99,
        condition: 'used',
        location: 'San Antonio, TX',
        latitude: 29.4241,
        longitude: -98.4936,
        images: getProductImages('Sports & Recreation', 'Basketball'),
        status: 'active',
        views: 54,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
        updatedAt: DateTime.now().subtract(const Duration(days: 9)),
      ),
      Product(
        id: 135,
        userId: 3,
        categoryId: 5,
        title: 'Yoga Mat - Manduka Pro',
        description: 'Manduka Pro yoga mat in black. High-density and non-slip surface. Used for only a few classes, excellent condition. Perfect for yoga, Pilates, and other fitness activities.',
        price: 89.99,
        condition: 'used',
        location: 'Boulder, CO',
        latitude: 40.0150,
        longitude: -105.2700,
        images: getProductImages('Sports & Recreation', 'Yoga'),
        status: 'active',
        views: 67,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 11)),
        updatedAt: DateTime.now().subtract(const Duration(days: 11)),
      ),
      Product(
        id: 136,
        userId: 4,
        categoryId: 5,
        title: 'Coleman Camping Tent - 4 Person',
        description: 'Coleman 4-person camping tent in excellent condition. Easy setup and waterproof design. Used for only one camping trip. Includes carrying bag and all stakes.',
        price: 79.99,
        condition: 'used',
        location: 'Bend, OR',
        latitude: 44.0582,
        longitude: -121.3150,
        images: getProductImages('Sports & Recreation', 'Camping'),
        status: 'active',
        views: 45,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 13)),
        updatedAt: DateTime.now().subtract(const Duration(days: 13)),
      ),
      Product(
        id: 137,
        userId: 1,
        categoryId: 5,
        title: 'Schwinn Hybrid Bike - Excellent Condition',
        description: 'Schwinn hybrid bike with comfortable seat and smooth ride. Perfect for commuting or recreational riding. Recently serviced with new tires and brakes.',
        price: 249.00,
        condition: 'used',
        location: 'Berkeley, CA',
        latitude: 37.8717,
        longitude: -122.2720,
        images: [
          'https://images.unsplash.com/photo-1544191696-15693072e0b5?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 87,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        updatedAt: DateTime.now().subtract(const Duration(days: 15)),
      ),
      Product(
        id: 138,
        userId: 2,
        categoryId: 5,
        title: 'Hiking Boots - Merrell Moab 2',
        description: 'Merrell Moab 2 hiking boots in excellent condition. Waterproof and comfortable for long hikes. Used for only a few hikes, minimal wear. Size 10.',
        price: 79.99,
        condition: 'used',
        location: 'Asheville, NC',
        latitude: 35.5951,
        longitude: -82.5515,
        images: [
          'https://images.unsplash.com/photo-1543512214-317f0733a601?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1517423440497-a058c20315a4?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 65,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 17)),
        updatedAt: DateTime.now().subtract(const Duration(days: 17)),
      ),
      Product(
        id: 139,
        userId: 3,
        categoryId: 5,
        title: 'Fishing Rod and Reel Combo - Shimano',
        description: 'Shimano fishing rod and reel combo in excellent condition. Perfect for freshwater fishing. Includes tackle box with lures and accessories.',
        price: 99.00,
        condition: 'used',
        location: 'Minneapolis, MN',
        latitude: 44.9778,
        longitude: -93.2650,
        images: [
          'https://images.unsplash.com/photo-1579972344684-2896f7a4a991?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1579972344684-2896f7a4a991?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 54,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 19)),
        updatedAt: DateTime.now().subtract(const Duration(days: 19)),
      ),
      Product(
        id: 140,
        userId: 4,
        categoryId: 5,
        title: 'Skateboard - Element Complete',
        description: 'Element complete skateboard in excellent condition. Used for only a few sessions, minimal wear. Perfect for beginners or experienced skaters.',
        price: 59.99,
        condition: 'used',
        location: 'San Diego, CA',
        latitude: 32.7157,
        longitude: -117.1611,
        images: [
          'https://images.unsplash.com/photo-1508711904997-460e9c9ca6a1?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1508711904997-460e9c9ca6a1?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 43,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[4],
        createdAt: DateTime.now().subtract(const Duration(days: 21)),
        updatedAt: DateTime.now().subtract(const Duration(days: 21)),
      ),
    ]);

    // Books & Media products (10 products)
    allProducts.addAll([
      Product(
        id: 141,
        userId: 1,
        categoryId: 6,
        title: 'Harry Potter and the Sorcerer\'s Stone - First Edition',
        description: 'Harry Potter and the Sorcerer\'s Stone first edition hardcover book. Excellent condition, rare collectible item.',
        price: 299.99,
        condition: 'used',
        location: 'New York, NY',
        latitude: 40.7128,
        longitude: -74.0060,
        images: getProductImages('Books & Media', 'Harry Potter'),
        status: 'active',
        views: 156,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        updatedAt: DateTime.now().subtract(const Duration(days: 4)),
      ),
      Product(
        id: 142,
        userId: 2,
        categoryId: 6,
        title: 'The Beatles - Abbey Road Vinyl Record',
        description: 'The Beatles - Abbey Road vinyl record in excellent condition. Original pressing, rare collectible item.',
        price: 149.00,
        condition: 'used',
        location: 'Los Angeles, CA',
        latitude: 34.0522,
        longitude: -118.2437,
        images: getProductImages('Books & Media', 'Vinyl'),
        status: 'active',
        views: 123,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
        updatedAt: DateTime.now().subtract(const Duration(days: 6)),
      ),
      Product(
        id: 143,
        userId: 3,
        categoryId: 6,
        title: 'Introduction to Algorithms - Textbook',
        description: 'Introduction to Algorithms textbook by Cormen et al. Excellent condition, perfect for computer science students.',
        price: 79.99,
        condition: 'used',
        location: 'Cambridge, MA',
        latitude: 42.3736,
        longitude: -71.1097,
        images: getProductImages('Books & Media', 'Textbook'),
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        updatedAt: DateTime.now().subtract(const Duration(days: 8)),
      ),
      Product(
        id: 144,
        userId: 4,
        categoryId: 6,
        title: 'The Shawshank Redemption - DVD',
        description: 'The Shawshank Redemption DVD in excellent condition. Classic movie for any collection.',
        price: 9.99,
        condition: 'used',
        location: 'Seattle, WA',
        latitude: 47.6062,
        longitude: -122.3321,
        images: getProductImages('Books & Media', 'DVD'),
        status: 'active',
        views: 76,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        updatedAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
      Product(
        id: 145,
        userId: 1,
        categoryId: 6,
        title: 'Game of Thrones - Complete Series Blu-ray',
        description: 'Game of Thrones complete series on Blu-ray. Excellent condition, perfect for fans of the show.',
        price: 149.99,
        condition: 'used',
        location: 'San Francisco, CA',
        latitude: 37.7749,
        longitude: -122.4194,
        images: [
          'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1616530940355-351fabd9524b?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 112,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
        updatedAt: DateTime.now().subtract(const Duration(days: 12)),
      ),
      Product(
        id: 146,
        userId: 2,
        categoryId: 6,
        title: 'The Lord of the Rings - Book Set',
        description: 'The Lord of the Rings book set in hardcover. Excellent condition, classic fantasy series.',
        price: 99.00,
        condition: 'used',
        location: 'Austin, TX',
        latitude: 30.2672,
        longitude: -97.7431,
        images: [
          'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 87,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 14)),
        updatedAt: DateTime.now().subtract(const Duration(days: 14)),
      ),
      Product(
        id: 147,
        userId: 3,
        categoryId: 6,
        title: 'The Dark Knight Trilogy - Blu-ray',
        description: 'The Dark Knight Trilogy on Blu-ray. Excellent condition, Christopher Nolan\'s Batman films.',
        price: 49.99,
        condition: 'used',
        location: 'Denver, CO',
        latitude: 39.7392,
        longitude: -104.9903,
        images: [
          'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1616530940355-351fabd9524b?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 65,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 16)),
        updatedAt: DateTime.now().subtract(const Duration(days: 16)),
      ),
      Product(
        id: 148,
        userId: 4,
        categoryId: 6,
        title: 'Programming: Principles and Practice Using C++',
        description: 'Programming: Principles and Practice Using C++ by Bjarne Stroustrup. Excellent condition, computer science textbook.',
        price: 69.00,
        condition: 'used',
        location: 'Portland, OR',
        latitude: 45.5051,
        longitude: -122.6750,
        images: [
          'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 54,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 18)),
        updatedAt: DateTime.now().subtract(const Duration(days: 18)),
      ),
      Product(
        id: 149,
        userId: 1,
        categoryId: 6,
        title: 'Thriller - Michael Jackson Vinyl',
        description: 'Thriller - Michael Jackson vinyl record. Excellent condition, classic album.',
        price: 79.99,
        condition: 'used',
        location: 'Nashville, TN',
        latitude: 36.1627,
        longitude: -86.7816,
        images: [
          'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1526394931762-8a4116f6e8c7?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        updatedAt: DateTime.now().subtract(const Duration(days: 20)),
      ),
      Product(
        id: 150,
        userId: 2,
        categoryId: 6,
        title: 'Pride and Prejudice - Jane Austen Book',
        description: 'Pride and Prejudice by Jane Austen. Excellent condition, classic novel.',
        price: 29.00,
        condition: 'used',
        location: 'Richmond, VA',
        latitude: 37.5407,
        longitude: -77.4360,
        images: [
          'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1551269901-5c5e14c25df7?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 76,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[5],
        createdAt: DateTime.now().subtract(const Duration(days: 22)),
        updatedAt: DateTime.now().subtract(const Duration(days: 22)),
      ),
    ]);

    // Pets & Animals products (10 products)
    allProducts.addAll([
      Product(
        id: 151,
        userId: 3,
        categoryId: 7,
        title: 'Dog Crate - Large Size',
        description: 'Large dog crate in excellent condition. Perfect for training or travel. Includes removable tray and carrying handle.',
        price: 49.99,
        condition: 'used',
        location: 'Phoenix, AZ',
        latitude: 33.4484,
        longitude: -112.0740,
        images: getProductImages('Pets & Animals', 'Dog Crate'),
        status: 'active',
        views: 134,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      Product(
        id: 152,
        userId: 4,
        categoryId: 7,
        title: 'Cat Tree - Multi-Level',
        description: 'Multi-level cat tree with scratching posts and perches. Excellent condition, provides hours of entertainment for your cat.',
        price: 79.00,
        condition: 'used',
        location: 'Tucson, AZ',
        latitude: 32.2217,
        longitude: -110.9260,
        images: getProductImages('Pets & Animals', 'Cat Tree'),
        status: 'active',
        views: 112,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 7)),
        updatedAt: DateTime.now().subtract(const Duration(days: 7)),
      ),
      Product(
        id: 153,
        userId: 1,
        categoryId: 7,
        title: 'Aquarium - 20 Gallon',
        description: '20-gallon aquarium with filter, heater, and LED light. Perfect for freshwater fish. Includes gravel and decorations.',
        price: 69.99,
        condition: 'used',
        location: 'San Diego, CA',
        latitude: 32.7157,
        longitude: -117.1611,
        images: getProductImages('Pets & Animals', 'Aquarium'),
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
        updatedAt: DateTime.now().subtract(const Duration(days: 9)),
      ),
      Product(
        id: 154,
        userId: 2,
        categoryId: 7,
        title: 'Bird Cage - Large Size',
        description: 'Large bird cage with perches and food bowls. Perfect for parrots or other large birds. Includes removable tray for easy cleaning.',
        price: 59.00,
        condition: 'used',
        location: 'Albuquerque, NM',
        latitude: 35.0844,
        longitude: -106.6500,
        images: getProductImages('Pets & Animals', 'Bird Cage'),
        status: 'active',
        views: 76,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 11)),
        updatedAt: DateTime.now().subtract(const Duration(days: 11)),
      ),
      Product(
        id: 155,
        userId: 3,
        categoryId: 7,
        title: 'Dog Bed - Memory Foam',
        description: 'Memory foam dog bed in excellent condition. Provides comfortable support for your dog\'s joints. Removable and washable cover.',
        price: 39.99,
        condition: 'used',
        location: 'Oklahoma City, OK',
        latitude: 35.4676,
        longitude: -97.5164,
        images: [
          'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 87,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 13)),
        updatedAt: DateTime.now().subtract(const Duration(days: 13)),
      ),
      Product(
        id: 156,
        userId: 4,
        categoryId: 7,
        title: 'Cat Scratching Post - Sisal Rope',
        description: 'Cat scratching post with durable sisal rope. Provides a healthy outlet for your cat\'s scratching instincts. Helps protect your furniture.',
        price: 29.00,
        condition: 'used',
        location: 'Dallas, TX',
        latitude: 32.7767,
        longitude: -96.7970,
        images: [
          'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 65,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
        updatedAt: DateTime.now().subtract(const Duration(days: 15)),
      ),
      Product(
        id: 157,
        userId: 1,
        categoryId: 7,
        title: 'Fish Tank Decorations - Assorted',
        description: 'Assorted fish tank decorations including plants, rocks, and ornaments. Adds visual interest to your aquarium.',
        price: 19.99,
        condition: 'used',
        location: 'Houston, TX',
        latitude: 29.7604,
        longitude: -95.3698,
        images: [
          'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 54,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 17)),
        updatedAt: DateTime.now().subtract(const Duration(days: 17)),
      ),
      Product(
        id: 158,
        userId: 2,
        categoryId: 7,
        title: 'Parrot Play Stand - Wood',
        description: 'Wooden parrot play stand with perches, ladders, and toys. Provides a stimulating environment for your parrot.',
        price: 89.00,
        condition: 'used',
        location: 'New Orleans, LA',
        latitude: 29.9511,
        longitude: -90.0715,
        images: [
          'https://images.unsplash.com/photo-1520808663317-647b476a81b9?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 43,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 19)),
        updatedAt: DateTime.now().subtract(const Duration(days: 19)),
      ),
      Product(
        id: 159,
        userId: 3,
        categoryId: 7,
        title: 'Hamster Cage - Multi-Level',
        description: 'Multi-level hamster cage with wheel, water bottle, and food bowl. Provides a stimulating environment for your hamster.',
        price: 39.99,
        condition: 'used',
        location: 'Kansas City, MO',
        latitude: 39.0997,
        longitude: -94.5786,
        images: [
          'https://images.unsplash.com/photo-1575444720364-94fa9a1355c4?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1575444720364-94fa9a1355c4?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 54,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 21)),
        updatedAt: DateTime.now().subtract(const Duration(days: 21)),
      ),
      Product(
        id: 160,
        userId: 4,
        categoryId: 7,
        title: 'Rabbit Hutch - Indoor/Outdoor',
        description: 'Indoor/outdoor rabbit hutch with wire mesh and wooden frame. Provides a safe and comfortable home for your rabbit.',
        price: 99.00,
        condition: 'used',
        location: 'Omaha, NE',
        latitude: 41.2524,
        longitude: -95.9980,
        images: [
          'https://images.unsplash.com/photo-1599344354945-e799336d759d?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1599344354945-e799336d759d?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 32,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[6],
        createdAt: DateTime.now().subtract(const Duration(days: 23)),
        updatedAt: DateTime.now().subtract(const Duration(days: 23)),
      ),
    ]);

    // Services products (10 products)
    allProducts.addAll([
      Product(
        id: 161,
        userId: 1,
        categoryId: 8,
        title: 'Web Development Services - Custom Website',
        description: 'Professional web development services for creating a custom website tailored to your business needs.',
        price: 999.99,
        condition: 'new',
        location: 'San Jose, CA',
        latitude: 37.3382,
        longitude: -121.8863,
        images: getProductImages('Services', 'Web Development'),
        status: 'active',
        views: 145,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
        updatedAt: DateTime.now().subtract(const Duration(days: 6)),
      ),
      Product(
        id: 162,
        userId: 2,
        categoryId: 8,
        title: 'Photography Services - Wedding Photography',
        description: 'Professional photography services for capturing your special day. Includes pre-wedding consultation and high-resolution images.',
        price: 1499.00,
        condition: 'new',
        location: 'Las Vegas, NV',
        latitude: 36.1699,
        longitude: -115.1398,
        images: getProductImages('Services', 'Photography'),
        status: 'active',
        views: 123,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
        updatedAt: DateTime.now().subtract(const Duration(days: 8)),
      ),
      Product(
        id: 163,
        userId: 3,
        categoryId: 8,
        title: 'Cleaning Services - House Cleaning',
        description: 'Reliable house cleaning services for keeping your home sparkling clean. Includes dusting, vacuuming, and mopping.',
        price: 99.00,
        condition: 'new',
        location: 'Sacramento, CA',
        latitude: 38.5816,
        longitude: -121.4944,
        images: getProductImages('Services', 'Cleaning'),
        status: 'active',
        views: 112,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
        updatedAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
      Product(
        id: 164,
        userId: 4,
        categoryId: 8,
        title: 'Tutoring Services - Math Tutoring',
        description: 'Experienced math tutor offering personalized tutoring sessions for students of all ages. Covers algebra, calculus, and more.',
        price: 49.99,
        condition: 'new',
        location: 'Fresno, CA',
        latitude: 36.7468,
        longitude: -119.7726,
        images: getProductImages('Services', 'Tutoring'),
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
        updatedAt: DateTime.now().subtract(const Duration(days: 12)),
      ),
      Product(
        id: 165,
        userId: 1,
        categoryId: 8,
        title: 'Graphic Design Services - Logo Design',
        description: 'Professional graphic design services for creating a unique and memorable logo for your brand.',
        price: 299.00,
        condition: 'new',
        location: 'Oakland, CA',
        latitude: 37.8044,
        longitude: -122.2711,
        images: [
          'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 134,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 14)),
        updatedAt: DateTime.now().subtract(const Duration(days: 14)),
      ),
      Product(
        id: 166,
        userId: 2,
        categoryId: 8,
        title: 'Plumbing Services - Emergency Repairs',
        description: 'Reliable plumbing services for emergency repairs. Available 24/7 for burst pipes, leaks, and other plumbing issues.',
        price: 149.00,
        condition: 'new',
        location: 'Long Beach, CA',
        latitude: 33.7701,
        longitude: -118.1937,
        images: [
          'https://images.unsplash.com/photo-1519389950473-47a880702a44?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1519389950473-47a880702a44?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 112,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 16)),
        updatedAt: DateTime.now().subtract(const Duration(days: 16)),
      ),
      Product(
        id: 167,
        userId: 3,
        categoryId: 8,
        title: 'Electrical Services - Home Wiring',
        description: 'Professional electrical services for home wiring and repairs. Licensed and insured electricians.',
        price: 199.00,
        condition: 'new',
        location: 'Anaheim, CA',
        latitude: 33.8353,
        longitude: -117.9145,
        images: [
          'https://images.unsplash.com/photo-1485291571150-772bcfc069ea?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1485291571150-772bcfc069ea?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 98,
        isFeatured: false,
        user: sampleUsers[2],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 18)),
        updatedAt: DateTime.now().subtract(const Duration(days: 18)),
      ),
      Product(
        id: 168,
        userId: 4,
        categoryId: 8,
        title: 'Landscaping Services - Lawn Care',
        description: 'Reliable landscaping services for lawn care and maintenance. Includes mowing, edging, and fertilization.',
        price: 79.00,
        condition: 'new',
        location: 'Riverside, CA',
        latitude: 33.9533,
        longitude: -117.3962,
        images: [
          'https://images.unsplash.com/photo-1501710895850-5122edc44903?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1501710895850-5122edc44903?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 76,
        isFeatured: false,
        user: sampleUsers[3],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
        updatedAt: DateTime.now().subtract(const Duration(days: 20)),
      ),
      Product(
        id: 169,
        userId: 1,
        categoryId: 8,
        title: 'Personal Training Services - Fitness Coaching',
        description: 'Certified personal trainer offering personalized fitness coaching and workout plans.',
        price: 59.99,
        condition: 'new',
        location: 'Santa Barbara, CA',
        latitude: 34.4208,
        longitude: -119.6982,
        images: [
          'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 65,
        isFeatured: false,
        user: sampleUsers[0],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 22)),
        updatedAt: DateTime.now().subtract(const Duration(days: 22)),
      ),
      Product(
        id: 170,
        userId: 2,
        categoryId: 8,
        title: 'Moving Services - Local Moving',
        description: 'Reliable moving services for local moves. Includes packing, loading, and transportation.',
        price: 299.00,
        condition: 'new',
        location: 'Bakersfield, CA',
        latitude: 35.3733,
        longitude: -119.0187,
        images: [
          'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=500&h=500&fit=crop',
          'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=500&h=500&fit=crop',
        ],
        status: 'active',
        views: 54,
        isFeatured: false,
        user: sampleUsers[1],
        category: sampleCategories[7],
        createdAt: DateTime.now().subtract(const Duration(days: 24)),
        updatedAt: DateTime.now().subtract(const Duration(days: 24)),
      ),
    ]);

    return allProducts;
  }

  static List<Category> getSampleCategories() {
    return [
      Category(
        id: 1,
        name: 'Electronics',
        slug: 'electronics',
        description: 'Phones, laptops, tablets, and electronic devices',
        icon: 'smartphone',
        isActive: true,
        productsCount: 10,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Category(
        id: 2,
        name: 'Vehicles',
        slug: 'vehicles',
        description: 'Cars, motorcycles, bicycles, and automotive parts',
        icon: 'car',
        isActive: true,
        productsCount: 10,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Category(
        id: 3,
        name: 'Home & Garden',
        slug: 'home-garden',
        description: 'Furniture, appliances, and garden equipment',
        icon: 'home',
        isActive: true,
        productsCount: 10,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Category(
        id: 4,
        name: 'Fashion',
        slug: 'fashion',
        description: 'Clothing, shoes, accessories, and jewelry',
        icon: 'shirt',
        isActive: true,
        productsCount: 10,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Category(
        id: 5,
        name: 'Sports & Recreation',
        slug: 'sports-recreation',
        description: 'Sports equipment, outdoor gear, and fitness items',
        icon: 'dumbbell',
        isActive: true,
        productsCount: 10,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Category(
        id: 6,
        name: 'Books & Media',
        slug: 'books-media',
        description: 'Books, movies, music, and educational materials',
        icon: 'book',
        isActive: true,
        productsCount: 10,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Category(
        id: 7,
        name: 'Pets & Animals',
        slug: 'pets-animals',
        description: 'Pet supplies, animals, and pet services',
        icon: 'heart',
        isActive: true,
        productsCount: 10,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Category(
        id: 8,
        name: 'Services',
        slug: 'services',
        description: 'Professional services, tutoring, and consulting',
        icon: 'briefcase',
        isActive: true,
        productsCount: 10,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
    ];
  }

  static List<User> getSampleUsers() {
    return [
      User(
        id: 1,
        name: 'John Smith',
        email: 'john@example.com',
        phone: '+1234567890',
        address: '123 Main St, New York, NY',
        latitude: 40.7128,
        longitude: -74.0060,
        role: 'seller',
        avatar: null,
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      User(
        id: 2,
        name: 'Sarah Johnson',
        email: 'sarah@example.com',
        phone: '+1234567891',
        address: '456 Oak Ave, Los Angeles, CA',
        latitude: 34.0522,
        longitude: -118.2437,
        role: 'seller',
        avatar: null,
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      User(
        id: 3,
        name: 'Mike Wilson',
        email: 'mike@example.com',
        phone: '+1234567892',
        address: '789 Pine St, Chicago, IL',
        latitude: 41.8781,
        longitude: -87.6298,
        role: 'seller',
        avatar: null,
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      User(
        id: 4,
        name: 'Emily Davis',
        email: 'emily@example.com',
        phone: '+1234567893',
        address: '321 Elm St, Houston, TX',
        latitude: 29.7604,
        longitude: -95.3698,
        role: 'seller',
        avatar: null,
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
    ];
  }
}
